import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

/**
 * data/gazetteer.seed.json -> src/lib/gazetteer.gen.ts.
 *
 * The gazetteer was costing D1 roughly seven hundred row reads on every
 * homepage view, spent re-deriving which cities sit inside Karnataka from 338
 * rows that had not changed since they were seeded. It cannot drift the way
 * cluster data does: the seed file is the declared source of truth, and
 * changing it means a commit, which means a redeploy. So it belongs in the
 * bundle, not in a database.
 *
 * Run by `npm run gazetteer:gen`, and by prebuild so a stale file cannot ship.
 * The D1 tables stay — build-gazetteer.ts still loads them, and the pipeline
 * still resolves against local SQLite — but the Worker no longer reads them.
 */

const SEED = resolve(process.cwd(), 'data/gazetteer.seed.json');
const OUT = resolve(process.cwd(), 'src/lib/gazetteer.gen.ts');

type SeedPlace = {
  id: string; kind: 'city' | 'admin1' | 'country'; name: string; label: string; country: string;
  admin1_id: string | null; parent_id: string | null;
  lat: number | null; lon: number | null; population: number | null;
};
type SeedAlias = { alias: string; country: string; place_id: string };

const seed = JSON.parse(readFileSync(SEED, 'utf8')) as { places: SeedPlace[]; aliases: SeedAlias[] };

// Tuples, not objects: the same 338 rows as records cost about three times the
// bytes in repeated key names, all of which the Worker would parse on cold start.
const places = seed.places.map((p) => [
  p.id, p.kind, p.name, p.label, p.country,
  p.admin1_id, p.parent_id, p.lat, p.lon, p.population,
]);
const aliases = seed.aliases.map((a) => [a.alias, a.country, a.place_id]);

writeFileSync(OUT, `// Generated by scripts/gen-gazetteer.ts from data/gazetteer.seed.json.
// Do not edit: edit the seed and run \`npm run gazetteer:gen\`.

export type PlaceRow = [
  id: string, kind: 'city' | 'admin1' | 'country', name: string, label: string, country: string,
  admin1_id: string | null, parent_id: string | null,
  lat: number | null, lon: number | null, population: number | null,
];
export type AliasRow = [alias: string, country: string, place_id: string];

export const PLACES: PlaceRow[] = ${JSON.stringify(places)};

export const ALIASES: AliasRow[] = ${JSON.stringify(aliases)};
`);

console.log(`${OUT}: ${places.length} places, ${aliases.length} aliases`);
